version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: rag-backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - qdrant
      - redis
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: rag-frontend
    environment:
      - REACT_APP_BACKEND=http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  qdrant_storage:
